name: scope2screen2
channels:
  - conda-forge
dependencies:
  - python=3.7
  - Flask=1.1.2
  - jinja2==3.0.3
  - werkzeug==2.0.3
  - itsdangerous==2.0.1
  - flask-sqlalchemy
  - nomkl
  - numpy
  - opencv
  - orjson
  - pandas
  - pillow=8.1.1
  - requests
  - scikit-learn
  - scikit-image
  - scipy
  - tifffile=2021.4.8
  - waitress
  - zarr=2.10.1
  - pyinstaller
  - pip
  - pip:
      - ome-types==0.2.9
      - dask
      - dask[dataframe]



